FROM python:3-alpine3.19
WORKDIR /MY-APP

# Install the PostgreSQL development libraries
RUN apk update && apk add --no-cache postgresql-dev gcc python3-dev musl-dev

COPY . /MY-APP/

RUN pip install -r requirements.txt

EXPOSE 5000

CMD ["python", "./run.py"]
