FROM node:16-alpine

WORKDIR /MY-APP

# Copy the package.json and package-lock.json files
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port your application will run on
EXPOSE 3000

# Command to run your application
CMD ["npm", "start"]
